### ISSUE TITLE
Add CSS for scroll with floating header

### ISSUE THREAD

**Issue by practicalparticipation** [open-contracting/standard-collaborator#16]
The following [CSS work-around](http://nicolasgallagher.com/jump-links-and-viewport-positioning/demo/#method-B) is needed so that in-page links work correctly, and don't lead to text being hidden behind the floating header. 

``` css
h2:before, h3:before {
    display: block;
    content: "";
    height: 100px;
    margin: -100px 0px 0px;
}
```
